### PR TITLE
Added delete user functionality to view all users admin page

### PR DESCRIPTION
**Pull request by UFdylantosh**

### CODE REVIEW

**Review by Charlene999 — COMMENTED** [review]
Waiting on some clarification from the backend team on the level and class requirement for characters

**Comment by cwojtak** [comment]
Based on what I saw, the requirements stuff looks right
The selecting spells/items for character seems to only show items/spells if you have a level that's greater than or equal to the spell or item's level and only if the item or spell's class type equals the character's class type

**Comment by Charlene999** [comment]
So specifically in line 100 in spells.component.ts and line 103 in items.component.ts, you can see that the 
_"if (this.levelReqMet(items[i].LevelReq))"_ line has been commented out. I have a comment in line 102 of items.component.ts that shows that that function is being called so that the item will not show at all if the level requirement is not met (if an item has a level greater than the character's). I see that the html file calls this function but it still shows the item in the filtered items if the function is not called here; it just doesn't show the add and remove buttons. So I recommend leaving the conditional statement for the levelReqMet function in so that no random items and spells show so for filtered items and spells, only the items and spells matching the requirements for class and level will show. When you run the code, you see that a user can click on their character and see all items for the matching class even if their character's level is lower than the item or spell's level. So that conditional statement ensures that the filtered items only show if the item's class matches and its level is less than or equal to the character's level

**Comment by UFdylantosh** [comment]
This issue should be resolved in a subsequent PR. Specifically #201. Two new pages were created, as agreed upon in the group meeting. The two new pages implement the functionality Charlene specifies above. The old spells and items pages will show all spells and items available by class regardless of level.

**Review by Charlene999 — APPROVED** [review]

**Pull request merged**
