### PR TITLE
Added ability to view all items and spells on init to /spells and /items pages

### PR DESCRIPTION
**Pull request by UFdylantosh**

### CODE REVIEW

**Review by Charlene999 — COMMENTED** [review]
Why is there classes stuff on these pages, shouldn't they just have items and spells viewed, since classes has its own page view

**Comment by UFdylantosh** [comment]
Class stuff is there for the All Items and All Spells views. If an end user wants to explore all the class spell or item options at once after clicking on another class option, those options enable the end user the ability to do so. Previously, once a user clicked on a class option, there was no way to obtain the all items and all spells view again.

**Comment by Charlene999** [comment]
For class stuff all we agreed on was that the classes page would have stuff for the classes not the items and spells pages, so I don't know why there is class title info on the items and spells pages, shouldn't they just have all items and spells?

**Comment by UFdylantosh** [comment]
The only thing agreed upon in the meeting was that I was to add content to the classes page. When asked for opinions on how or what should be implemented, nothing was established or agreed upon. 

For the spells and items pages, we agreed to create two new pages that display items and spells based on character level, and the old spells and items pages would display all the items in the database. With this in mind, the current implementation has a default display of displaying all spells and items to the user on the spells and items pages respectively. However, it also has a dropdown bar where a user can search for items and spells related to a specific class. 

I stand by this design choice, as it keeps item and spell information strictly confined to the spells and items pages, while also showing users which spell and item is associated with each class. To add items and spells tables to the classes page is more confusing and would serve no additional purpose if the functionality already exists in the items and spells pages.

If there is still an issue with this design decision, then I will ask the backend team if they have a problem with this implementation, and to report their opinions here.

**Comment by Charlene999** [comment]
There was never a plan to have any items or spell information on the classes page, and I do not know why you have decided to have class information on the spells and items' pages either, obviously these spells and items pages are just a copy of the code I wrote for viewing items and spells per character. The problem at hand is that I do not know why there is class selection ability on the spells and items pages, since they should just be showing the spell and item information, as the users page, the admin items and spells pages, and the character pages also only show information for their specific functionality.  I believe we do need to present this to the backend as this is something that will likely not be resolved here.

**Review by cwojtak — APPROVED** [review]

**Pull request merged**
